[#ftl]

[#assign DIAGRAMSTEST_LAMBDA_RESOURCE_TYPE = "lambda" ]
[#assign DIAGRAMSTEST_LAMBDA_FUNCTION_RESOURCE_TYPE = "function" ]

[@addServiceResource
    provider=DIAGRAMSTEST_PROVIDER
    service=DIAGRAMSTEST_LAMBDA_SERVICE
    resource=DIAGRAMSTEST_LAMBDA_RESOURCE_TYPE
/]

[@addServiceResource
    provider=DIAGRAMSTEST_PROVIDER
    service=DIAGRAMSTEST_LAMBDA_SERVICE
    resource=DIAGRAMSTEST_LAMBDA_FUNCTION_RESOURCE_TYPE
/]
