name: release

on:
  push:
    branches:
      - 'main'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:

jobs:
  diagram_draw_test:
    runs-on: ubuntu-latest
    env:
      HAMLET_ENGINE: unicycle
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: |
          pip install hamlet
          sudo apt-get install -y graphviz

      - name: Run Diagram Generation
        env:
          GENERATION_PLUGIN_DIRS: ${{ github.workspace }}
        run: |
          hamlet engine get-engine
          hamlet -i mock -p diagramstest -p diagrams visual draw-diagrams -d "diagrams/"

  package:
    uses: hamlet-io/.github/.github/workflows/engine_image_release.yml@1.1.1
    if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags') }}
    with:
      defaultBranchName: main
    secrets: inherit
