name: release

on:
  push:
    branches:
      - 'main'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:

jobs:
  diagram_draw_test:
    runs-on: ubuntu-latest
    env:
      HAMLET_ENGINE: unicycle
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Java Setup
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Install
        run: |
          pip install hamlet
          sudo apt-get install -y graphviz

      - name: Run Diagram Generation
        env:
          GENERATION_PLUGIN_DIRS: ${{ github.workspace }}
        run: |
          hamlet engine get-engine
          hamlet -i mock -p diagramstest -p diagrams visual draw-diagrams -d "diagrams/"



  package:
    needs:
      - diagram_draw_test

    if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags') }}
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: add build details
        run: |
          pip install hamlet
          hamlet engine add-engine-source-build

      - name: docker meta details
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{github.repository}}
          flavor: |
            latest=auto
          tags: |
            type=semver,pattern={{version}}
            type=edge,branch=main
            type=sha

      - name: build and push container
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: base_package
